apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: fogcat5/weather:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz  # The endpoint your app exposes for health checks
            port: 8080
          initialDelaySeconds: 5  # Wait 5 seconds after the container starts before checking
          periodSeconds: 10       # Check every 10 seconds
        livenessProbe:
          httpGet:
            path: /healthz  # The endpoint your app exposes for liveness checks
            port: 8080
          initialDelaySeconds: 10  # Wait 10 seconds after the container starts before the first check
          periodSeconds: 30        # Check every 30 seconds
