apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"  # Redirect HTTP to HTTPS
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - weather.fogcat5.com
    secretName: weather-tls
  rules:
  - host: weather.fogcat5.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: weather-service
            port:
              number: 80
      - path: /timelapse
        pathType: Prefix
        backend:
          service:
            name: timelapse-web
            port:
              number: 5000
      - path: /gif
        pathType: Prefix
        backend:
          service:
            name: timelapse-web
            port:
              number: 5000
      - path: /frames
        pathType: Prefix
        backend:
          service:
            name: timelapse-web
            port:
              number: 5000
      - path: /thumbnails
        pathType: Prefix
        backend:
          service:
            name: timelapse-web
            port:
              number: 5000
