apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-ingress
  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"  # Redirect HTTP to HTTPS
    nginx.ingress.kubernetes.io/custom-http-errors: "404"   # Trigger custom handling for 404 errors
    nginx.ingress.kubernetes.io/error-page: "/404.html"      # Custom error page to redirect
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - weather.fogcat5.com
    secretName: weather-tls
  rules:
  - host: weather.fogcat5.com
    http:
      paths:
      - path: /collector/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: collector-webapp-service
            port:
              number: 80
      - path: /(frames.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: timelapse-web
            port:
              number: 5000
      - path: /(gif.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: timelapse-web
            port:
              number: 5000
      - path: /(timelapse.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: timelapse-web
            port:
              number: 5000
      - path: /(thumbnails.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: timelapse-web
            port:
              number: 5000
      - path: /weather.png
        pathType: ImplementationSpecific
        backend:
          service:
            name: weather-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: weather-service
            port:
              number: 80