name: Build Docker Image

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (or another container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            fogcat5/weather:latest
            fogcat5/weather:${{ github.sha }}

      # Set up kubeconfig
      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig


      - name: Authenticate to GKE
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GKE
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: my-first-cluster
          location: us-west1-a
          project_id: k8s-project-441922

      - name: Verify Kubernetes cluster access
        run: kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/weather weather=fogcat5/weather:${{ github.sha }}
          kubectl rollout status deployment/weather
